timeoverflow-develop/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get "global/switch_lang", as: :switch_lang

  resources :offers do
    collection do
      get :dashboard
    end
  end

  resources :inquiries

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, concerns: :accountable do
    member do
      post :set_current
    end
  end

  resources :users, concerns: :accountable, except: :destroy, :path => "members"

  resources :transfers, only: [:create] do
    member do
      put :delete_reason
    end
  end

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
    end
  end

  resource "statistics" do
    collection do
      get "statistics_global_activity"
      get "statistics_inactive_users"
      get "statistics_demographics"
      get "statistics_last_login"
      get "statistics_without_offers"
      get "statistics_type_swaps"
      get "statistics_all_transfers"
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get "alpha_grouped_index"
      get "inquiries"
      get "offers"
    end
  end

end

timeoverflow-develop/app/models/offer.rb
class Offer < Post
end

timeoverflow-develop/app/controllers/offers_controller.rb
# Managems of offer-type posts
#
class OffersController < PostsController
  def model
    Offer
  end

  def dashboard
    initial_scope =
      if current_organization
        current_organization.offers.active.of_active_members
      else
        Offer.all.active.of_active_members
      end
    @offers = Category.all.sort_by { |a| a.name.downcase }.
              each_with_object({}) do |category, offers|
      list = initial_scope.merge(category.posts).limit(5)
      offers[category] = list if list.present?
    end
  end
end

timeoverflow-develop/app/views/offers/dashboard.html.erb
<h1>
  <%= Offer.model_name.human(count: :many) %>
  <%= render "shared/show_filter_hint" %>
</h1>
<div class="navbar">
  <form action="<%= offers_path %>"
        class="navbar-form navbar-left"
        method="get"
        role="search">
    <div class="form-group">
      <input class="form-control"
             name="q"
             placeholder="<%= t "global.search" %>"
             type="text"
             value="<%= params[:q] %>">
    </div>
    <button class="btn btn-default" type="submit">
      <%= t("global.search") %>
    </button>
  </form>
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a class="dropdown-toggle" href="#">
        <%= @category ? @category.name : Category.model_name.human %>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "× #{t "global.all"}", offers_path %>
        </li>
        <% Category.all.sort_by { |a| a.name.downcase }.each do |c| %>
          <% next if c == @category %>
          <li>
            <%= link_to c.name, offers_path(cat: c.id) %>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <li>
      <%= link_to new_offer_path do %>
        <%= glyph :plus %>
        <%= t "helpers.submit.create", model: Offer.model_name.human %>
      <% end %>
    </li>
  </ul>
</div>
<% @offers.each do |cat, offs| %>
  <div class="offers">
    <h3>
      <%= cat.name.capitalize %>
    </h3>
    <%= render 'shared/posts', posts: offs %>
  </div>
  <%= link_to offers_path(cat: cat.id), class: "more btn btn-primary" do %>
    <%= t('global.more') %>
  <% end %>
<% end %>

timeoverflow-develop/app/views/offers/edit.html.erb
<h1>
  <%= @offer.title %>
  <small><%= t ".edit" %></small>
</h1>
<%= render 'shared/post_form', post: @offer, label_button: t(".submit") %>

timeoverflow-develop/app/views/offers/index.html.erb
<h1>
  <% @category = Category.where(id: params[:cat]).first %>
  <%= Offer.model_name.human(count: :many) %>
  <%= render "shared/show_filter_hint" %>
</h1>
<div class="navbar">
  <form action="<%= offers_path %>"
        class="navbar-form navbar-left"
        method="get"
        role="search">
    <div class="form-group">
      <input class="form-control"
             name="q"
             placeholder="<%= t 'global.search' %>"
             type="text"
             value="<%= params[:q] %>">
    </div>
    <button class="btn btn-default" type="submit">
      <%= t 'global.search' %>
    </button>
  </form>
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a class="dropdown-toggle" href="#">
        <%= @category ? @category.name : Category.model_name.human %>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "× #{t 'global.all'}", dashboard_offers_path %>
        </li>
        <% Category.all.sort_by { |a| a.name.downcase }.each do |c| %>
          <% next if c == @category %>
          <li>
            <%= link_to c.name, offers_path(cat: c.id) %>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
  <% if current_user && current_organization && !params[:org] %>
    <ul class="nav navbar-nav pull-right">
      <li>
        <%= link_to new_offer_path do %>
          <%= glyph :plus %>
          <%= t "helpers.submit.create", model: Offer.model_name.human %>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>
<div class="offers">
  <%= render "shared/posts", posts: @offers %>
</div>
<%= paginate @offers %>

timeoverflow-develop/app/views/offers/index.js.erb
$(".offers").append("<%= j render('shared/posts', posts: @offers) %>");
$(".offers ~ a[rel=next]").replaceWith("<%= j link_to_next_page(@offers, t('.more'), remote: true, params: params) %>");

timeoverflow-develop/app/views/offers/new.html.erb
<h1>
  <%= t "helpers.submit.create", model: @offer.class.model_name.human %>
</h1>
<%= render 'shared/post_form', post: @offer, label_button: t(".submit") %>

timeoverflow-develop/app/views/offers/show.html.erb
<p class="actions text-right">
  <% if admin? or @offer.user == current_user %>
    <%= link_to edit_offer_path(@offer), class: "btn btn-warning" do %>
      <%= glyph :pencil %>
      <%= t "global.edit" %>
    <% end %>
    <%= link_to @offer,
                data: { method: :DELETE, confirm: "sure?" },
                class: "btn btn-danger" do %>
      <%= glyph :trash %>
      <%= t "global.delete" %>
    <% end %>
  <% end %>
  <% if current_user and @offer.user != current_user %>
    <%= link_to give_time_user_path(@offer.user, offer: @offer.id),
                class: "btn btn-success" do %>
      <%= glyph :time %>
      <%= t ".give_time_for" %>
    <% end %>
  <% end %>
</p>
<%= render "shared/post", post: @offer %>