timeoverflow-develop/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get "global/switch_lang", as: :switch_lang

  resources :offers do
    collection do
      get :dashboard
    end
  end

  resources :inquiries

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, concerns: :accountable do
    member do
      post :set_current
    end
  end

  resources :users, concerns: :accountable, except: :destroy, :path => "members"

  resources :transfers, only: [:create] do
    member do
      put :delete_reason
    end
  end

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
    end
  end

  resource "statistics" do
    collection do
      get "statistics_global_activity"
      get "statistics_inactive_users"
      get "statistics_demographics"
      get "statistics_last_login"
      get "statistics_without_offers"
      get "statistics_type_swaps"
      get "statistics_all_transfers"
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get "alpha_grouped_index"
      get "inquiries"
      get "offers"
    end
  end

end

timeoverflow-develop/app/models/inquiry.rb
class Inquiry < Post
end

timeoverflow-develop/app/controllers/inquiries_controller.rb
class InquiriesController < PostsController
  def model
    Inquiry
  end
end

timeoverflow-develop/app/views/inquiries/edit.html.erb
<h1>
  <%= @inquiry.title %>
  <small><%= t ".edit" %></small>
</h1>
<%= render "shared/post_form", post: @inquiry, label_button: t(".submit") %>

timeoverflow-develop/app/views/inquiries/index.html.erb
<% @category = Category.where(id: params[:cat]).first %>
<h1>
  <%= Inquiry.model_name.human(count: :many) %>
  <%= render "shared/show_filter_hint" %>
</h1>

<div class="navbar">
  <form action="<%= inquiries_path %>"
        class="navbar-form navbar-left"
        method="get"
        role="search">
    <div class="form-group">
      <input class="form-control"
             name="q"
             placeholder="<%= t("global.search") %>"
             type="text"
             value="<%= params[:q] %>">
    </div>
    <button class="btn btn-default" type="submit">
      <%= t("global.search") %>
    </button>
  </form>
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a class="dropdown-toggle" href="#">
        <%= @category ? @category.name : Category.model_name.human %>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "× #{t("global.all")}", inquiries_path %>
        </li>
        <% Category.all.sort_by { |a| a.name.downcase }.each do |c| %>
          <% next if c == @category %>
          <li>
            <%= link_to c.name, inquiries_path(cat: c.id) %>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
  <% if current_user && current_organization && !params[:org] %>
    <ul class="nav navbar-nav pull-right">
      <li>
        <%= link_to new_inquiry_path do %>
          <%= glyph :plus %>
          <%= t "helpers.submit.create", model: Inquiry.model_name.human %>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

<div class="inquiries">
  <%= render "shared/posts", posts: @inquiries %>
</div>
<%= paginate @inquiries %>

timeoverflow-develop/app/views/inquiries/index.js.erb
$('.inquiries').append('<%= j render("shared/posts", posts: @inquiries) %>');
$('.inquiries ~ a[rel=next]').replaceWith('<%= j link_to_next_page(@inquiries, t('.more'), remote: true, params: params) %>');

timeoverflow-develop/app/views/inquiries/new.html.erb
<h1>
  <%= t "helpers.submit.create", model: @inquiry.class.model_name.human %>
</h1>
<%= render 'shared/post_form', post: @inquiry, label_button: t(".submit") %>

timeoverflow-develop/app/views/inquiries/show.html.erb
<p class="actions text-right">
  <% if admin? || @inquiry.user == current_user %>
    <%= link_to edit_inquiry_path(@inquiry), class: "btn btn-warning" do %>
      <%= glyph :pencil %>
      <%= t "global.edit" %>
    <% end %>
    <%= link_to @inquiry,
                data: { method: :delete, confirm: "sure?" },
                class: "btn btn-danger" do %>
      <%= glyph :trash %>
      <%= t "global.delete" %>
    <% end %>
  <% end %>
</p>
<%= render "shared/post", post: @inquiry %>