timeoverflow-develop/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get "global/switch_lang", as: :switch_lang

  resources :offers do
    collection do
      get :dashboard
    end
  end

  resources :inquiries

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, concerns: :accountable do
    member do
      post :set_current
    end
  end

  resources :users, concerns: :accountable, except: :destroy, :path => "members"

  resources :transfers, only: [:create] do
    member do
      put :delete_reason
    end
  end

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
    end
  end

  resource "statistics" do
    collection do
      get "statistics_global_activity"
      get "statistics_inactive_users"
      get "statistics_demographics"
      get "statistics_last_login"
      get "statistics_without_offers"
      get "statistics_type_swaps"
      get "statistics_all_transfers"
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get "alpha_grouped_index"
      get "inquiries"
      get "offers"
    end
  end

end

timeoverflow-develop/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :members, dependent: :destroy
  has_many :users, -> { order "members.created_at DESC" }, through: :members
  has_many :all_accounts, class_name: "Account", inverse_of: :organization
  has_many :all_movements, class_name: "Movement", through: :all_accounts, source: :movements do
    def with_transfer
      joins(transfer: :movements)
    end
  end
  has_many :all_transfers, class_name: "Transfer", through: :all_movements, source: :transfer
  has_one :account, as: :accountable
  has_many :member_accounts, through: :members, source: :account
  has_many :posts
  has_many :offers
  has_many :inquiries
  has_many :documents, as: :documentable

  scope :matching, ->(str) {
    where(Organization.arel_table[:name].matches("%#{str}%"))
  }

  validates :name, uniqueness: true

  before_validation :ensure_url
  after_create :create_account

  def to_s
    "#{name}"
  end

  def ensure_reg_number_seq!
    update_column(:reg_number_seq, members.maximum(:member_uid))
  end

  def ensure_reg_number_seq
    ensure_reg_number_seq! unless reg_number_seq
  end

  def next_reg_number_seq
    ensure_reg_number_seq
    increment!(:reg_number_seq)
    reg_number_seq
  end

  def ensure_url
    return if web.blank? || URI.parse(web).is_a?(URI::HTTP)
  rescue
    errors.add(:web, :url_format_invalid)
  else
    if URI.parse("http://#{web}").is_a?(URI::HTTP)
      self.web = "http://#{web}"
    else
      errors.add(:web, :url_format_invalid)
    end
  end
end

timeoverflow-develop/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :load_resource

  def load_resource
    if params[:id]
      @organization = Organization.find(params[:id])
    else
      @organizations = Organization.all
    end
  end

  def new
    @organization = Organization.new
  end

  def index
    @organizations = @organizations.matching(params[:q]) if params[:q].present?
  end

  def show
    @movements = @organization.
                 account.
                 movements.
                 order("created_at DESC").
                 page(params[:page]).
                 per(10)
  end

  def create
    @organization = @organizations.build organization_params
    if @organization.save
      redirect_to @organization, status: :created
    else
      render action: :new, status: :unprocessable_entity
    end
  end

  def update
    if @organization.update_attributes(organization_params)
      redirect_to @organization
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path, notice: "deleted"
  end

  def give_time
    @destination = @organization.account.id
    @source = find_transfer_source
    @offer = find_transfer_offer
    @transfer = Transfer.new(source: @source, destination: @destination)
    @sources = find_transfer_sources_for_admin
  end

  def set_current
    if current_user
      session[:current_organization_id] = @organization.id
    end
    redirect_to root_path
  end

  private

  def organization_params
    params[:organization].permit(*%w[name theme email phone web
                                     public_opening_times description address
                                     neighborhood city domain])
  end

  def find_transfer_offer
    current_organization.offers.
      find(params[:offer]) if params[:offer].present?
  end

  def find_transfer_source
    current_user.members.
      find_by(organization: @organization).account.id
  end

  def find_transfer_sources_for_admin
    return unless admin?
    [current_organization.account] +
      current_organization.member_accounts.where("members.active is true")
  end
end

timeoverflow-develop/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

timeoverflow-develop/app/views/organizations/_form.html.erb
<%= simple_form_for @organization do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :web %>
  <%= f.input :description %>
  <%= f.input :public_opening_times %>
  <%= f.input :address %>
  <%= f.input :neighborhood %>
  <%= f.input :city %>
  <%= f.button :submit %>
<% end %>

timeoverflow-develop/app/views/organizations/edit.html.erb
<% if @organization.errors.present? %>
  <% @organization.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <%= msg %>
    </div>
  <% end %>
<% end %>
<h1>
  <%= link_to @organization, organization_path(@organization) %>
  <small><%= t 'global.edit' %></small>
</h1>
<%= render 'form' %>

timeoverflow-develop/app/views/organizations/give_time.html.erb
<h1>
  <small><%= t '.give_time' %></small>
  <%= link_to @organization, organization_path(@organization) %>
</h1>
<% if @offer %>
  <h3>
    <%= @offer %>
  </h3>
<% end %>
<%= simple_form_for @transfer do |f| %>
  <div class="form-inputs">
    <%= f.input :hours,
                as: :integer,
                input_html: {
                  min: 0,
                  max: 20,
                  'data-rule-either-hours-minutes-informed' => 'true',
                  'data-rule-range' => '[0,20]'
                } %>
    <%= f.input :minutes,
                as: :integer,
                input_html: {
                  min: 0,
                  max: 59,
                  step: 15,
                  'data-rule-either-hours-minutes-informed' => 'true',
                  'data-rule-range' => '[0,59]'
                } %>
    <%= f.input :amount, as: :hidden %>
    <%= f.input :reason %>
    <%= f.input :destination, as: :hidden %>
    <% if admin? %>
      <div class="form-group">
        <%= f.label :source %>
        <%# TODO: refactor. it's very complex for a view. %>
        <%= f.select :source,
                     options_for_select(
                       @sources.sort_by { |source| [source.accountable_type, source.accountable_id] }
                               .map { |a| ["#{a.accountable_type == 'Member' ? a.accountable.member_uid : a.accountable_id} #{a.accountable_type} #{a.accountable.to_s}", a.id] },
                       selected: current_user.member(current_organization).account.id
                     ),
                     {},
                     id: 'select2-time',
                     class: 'form-control' %>
      </div>
    <% end %>
    <% if @offer %>
      <%= f.input :post, as: :hidden %>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit,
                 class: 'btn btn-default',
                 style: 'margin-bottom: 20px;' %>
  </div>
<% end %>
<script>
  $("#select2-time").select2({
    formatNoMatches: function () {
        return "<%= j t('application.tips.user_not_found') %>";
    }
  });
</script>

timeoverflow-develop/app/views/organizations/index.html.erb
<h1>
  <%= Organization.model_name.human(count: :many) %>
</h1>

<ul class="nav nav-pills">
  <% if superadmin? %>
    <li>
      <%= link_to new_organization_path do %>
        <%= glyph :plus %>
        <%= t 'global.add_new' %>
      <% end %>
    </li>
  <% end %>
</ul>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th><%= Organization.model_name.human(count: :one) %></th>
      <th><%= t '.member_count' %></th>
      <th><%= glyph :wrench %><%= t 'global.table.actions' %></th>
    </tr>
  </thead>
  <tbody>
    <% @organizations.each do |org| %>
      <tr>
        <td><%= link_to org.name, org %></td>
        <td><%= org.users.count %></td>
        <td class="hover-actions">
          <% if current_user.admins?(org) %>
            <%= link_to edit_organization_path(org), class: 'action' do %>
              <%= glyph :pencil %>
              <%= t 'global.edit' %>
            <% end %>
            <%= link_to organization_path(org),
                        data: { method: :delete },
                        class: 'action' do %>
              <%= glyph :trash %>
              <%= t 'global.borrar' %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

timeoverflow-develop/app/views/organizations/new.html.erb
<h1>
  <%= t '.new' %>
</h1>
<%= render 'form' %>

timeoverflow-develop/app/views/organizations/show.html.erb
<h1>
  <%= link_to @organization, organization_path(@organization) %>
</h1>
<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t '.contact_information' %>
        </h3>
      </div>
      <div class="panel-body">
        <p>
          <strong>
            <%= Organization.human_attribute_name 'email' %>
          </strong>
          <%= @organization.email %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'phone' %>
          </strong>
          <%= @organization.phone %>
          <br/>
          <strong>Web</strong>
          <%= link_to_if @organization.web.present?,
                         @organization.web,
                         @organization.web %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'public_opening_times' %>
          </strong>
          <br/>
          <%= @organization.public_opening_times %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'address' %>
          </strong>
          <%= @organization.address %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'neighborhood' %>
          </strong>
          <%= @organization.neighborhood %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'city' %>
          </strong>
          <%= @organization.city %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t 'global.information' %>
        </h3>
      </div>
      <div class="panel-body">
        <p>
          <strong>
            <%= Organization.human_attribute_name 'created_at' %>
          </strong>
          <%= l @organization.created_at, format: :long %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'updated_at' %>
          </strong>
          <%= l @organization.updated_at, format: :long %>
          <br/>
          <strong>
            <%= t 'global.member_count' %>
          </strong>
          <%= @organization.members.count %>
          <br/>
          <strong>
            <%= t 'global.balance' %>
          </strong>
          <%= seconds_to_hm(@organization.account.try(:balance) || '—') %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-5">
    <ul class="nav nav-pills pull-right">
      <% if superadmin? %>
        <li>
          <%= link_to organizations_path do %>
            <%= glyph :hand_left %>
            <%= t 'global.back' %>
          <% end %>
        </li>
      <% end %>
      <% if admin? %>
        <li>
          <%= link_to edit_organization_path(@organization) do %>
            <%= glyph :pencil %>
            <%= t "global.edit" %>
          <% end %>
        </li>
      <% end %>
      <% if superadmin? %>
        <li>
          <%= link_to organization_path(@organization),
                      data: { method: :delete, confirm: t("are_you_sure") } do %>
            <%= glyph :trash %>
            <%= t "global.delete" %>
          <% end %>
        </li>
      <% end %>
      <li>
        <%= link_to give_time_organization_path(@organization) do %>
          <%= glyph :time %>
          <%= t "global.give_time" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<% if current_user %>
  <%= render "shared/movements" %>
<% end %>